version: '3.8'

services:
  web:
    build: .
    container_name: todo_django_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-dev-env-key-for-local-runs-only
    volumes:
      - .:/app
      - db_data:/app/db_volume
    restart: always

volumes:
  db_data:
