name: TaskFlow CI-CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Code Linting with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Code Formatting with black
      run: |
        # Run black formatting verification
        black --check . --exclude '/(\.git|\.venv)/'

    - name: Check Django Migrations
      run: |
        python manage.py makemigrations --check --dry-run

    - name: Run Django Unit Tests
      run: |
        python manage.py test

  build-docker:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Hub login
      run: |
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      env:
        DOCKERHUB_USERNAME: sethu90
        DOCKERHUB_TOKEN: xQeuUQU7KE7LE906gXdpkF6hHeQ
    - name: Push Docker Image
      run: |
        docker tag taskflow:latest sethu90/taskflow:latest
        docker push sethu90/taskflow:latest
      env:
        DOCKERHUB_USERNAME: sethu90
        DOCKERHUB_TOKEN: xQeuUQU7KE7LE906gXdpkF6hHeQ

    - name: Build and Verify Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: taskflow:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
